# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organization',
            field=models.CharField(default='sbh', max_length=280),
            preserve_default=False,
        ),
    ]
