# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_events_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='going',
            field=models.IntegerField(default=0),
        ),
    ]
