# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_events_going'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='going',
            new_name='rsvp',
        ),
    ]
