# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20160719_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
