# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_scores_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=120)),
                ('round', models.IntegerField(default=0)),
                ('court', models.IntegerField(default=0)),
                ('set', models.IntegerField(default=0)),
                ('playerwon', models.IntegerField(default=0)),
                ('playerloss', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
